/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dev_cristian_alvarez_usarcodigonativoc_ClaseNativa */

#ifndef _Included_com_dev_cristian_alvarez_usarcodigonativoc_ClaseNativa
#define _Included_com_dev_cristian_alvarez_usarcodigonativoc_ClaseNativa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dev_cristian_alvarez_usarcodigonativoc_ClaseNativa
 * Method:    sumar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dev_cristian_alvarez_usarcodigonativoc_ClaseNativa_sumar
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
